nx=256;
ny=256;
dx=0.5;
dy=0.5;
a=20;
b=30;
origin=[0,0];
phantom_params.nx=nx;
phantom_params.ny=ny;
phantom_params.dx=dx;
phantom_params.dy=dy;
phantom_params.origin=origin;
[xx,yy]=meshgrid(x,y);
eclipse=(xx.^2/a^2)+(yy.^2/b^2);
ph=zeros(nx,ny);
ph(eclipse<1)=1;
% figure(1);imshow(ph,[]);