% beam_center=[0, -50];
beam_SAD=50;
beam_angles=[0,50, 100, 150, 200, 250];
% beam_center=[beam_SAD*sind(beam_angle), beam_SAD*cosd(beam_angle)];
beam_energy=6000;
beam_nx=21;
% beam_ny=1;
beam_dx=0.25;
beam_dy=0.25;
% beam_x=beam_center(1)+cosd(beam_angle)*((0:beam_nx-1)-(beam_nx-1)/2)*beam_dx;
% beam_y=beam_center(2)-sind(beam_angle)*((0:beam_nx-1)-(beam_nx-1)/2)*beam_dx;
% source_params.beam_center=beam_center; % real coordinate
source_params.beam_SAD=beam_SAD;
source_params.beam_angles=beam_angles;
source_params.beam_energy=beam_energy; % keV
% source_params.beam_x=beam_x;
% source_params.beam_y=beam_y;
% source_params.beam_direction=[,0]; % direction vector
source_params.beam_dx=beam_dx;
% source_params.beam_dy=beam_dy;
source_params.beam_nx=beam_nx;
% source_params.beam_ny=beam_ny;
fluence_1d=ones(beam_nx,length(beam_angles));